---
title: "trying to make a mao"
author: "Joseph Kilgallen"
date: "2/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(tidyverse)
library(here)
library(bslib)
library(ggplot2)
library(shinythemes)
library(readxl)
library(magrittr)
library(rvest)
library(dplyr)
library(httr)
library(maps)
library(reshape2)
library(ggiraph)
library(RColorBrewer)
library(leaflet)
library(magrittr)
library(sf)
library(rvest)
library(tidyr)
library(maptools)
library(rgdal)
library(rworldmap)
library(sp)
library(plotly)
library(lubridate)
library(rAmCharts)
library(rsconnect)
library(shinydashboard)
library(DT)

# Read in the data
gender_data <- read_xlsx(here("data", "Gender.xlsx"))


# # Tidying the data
gender_mod <- gender_data %>%
  rename("HDI Rank" = ...1,
         "Country" = ...2,
         "Gender Equality Index '18" = ...3,
         "Rank '18" = ...5,
         "Maternal Mortality Ratio '15" = SDG3.1,
         "Adolescent Birth Rate '15-'20" = SDG3.7,
         "Seats in Parliment '18" = SDG5.5,
         "Secondary Education (F)'10-'18" = SDG4.6,
         "Secondary Education (M)'10-'18" = ...15,
         "Labour Force Participation (F)'18" = ...17,
         "Labour Force Participation (M)'18" = ...19) %>%
  select(-...4,-...6,-...8,-...10,-...12,-...14,-...16,-...18,-...20) %>%
  filter(!row_number() %in% c(1, 2, 3, 4, 5, 228:261))

```


### Making reactive data table
```{r}
## Creating a subset of the data to use to make the table
tab_data <- gender_mod %>% 
  janitor::clean_names()
## dropping rows that do not contain countries
tab_data <- tab_data %>% slice(-c(193, 200:222))
## need to drop some more--- 
tab_data <- tab_data %>% slice(-c(63, 118, 156))
## now putting in alphabetical order
tab_data <- tab_data %>% arrange(country)

### NEED TO CLEAN UP TABLE
# Interactive Data Table
tab_data_table <- tab_data %>%
  group_by(country, gender_equality_index_18) 

tab_data_table$Status <- NULL
```

## making interactive map
```{r}
## MAKING INTERACTIVE MAP
## creating a subset of the data to use to make a map
map_data <- gender_mod %>% 
  janitor::clean_names()
## dropping rows that do not contain countries
map_data <- map_data %>% slice(-c(193, 200:222))
## need to drop some more--- 
map_data <- map_data %>% slice(-c(63, 118, 156))
## now putting in alphabetical order
map_data <- map_data %>% arrange(country) %>% 
  rename(
    region = country
  )
## using base map data from ggplot to try to assemble em
base_map <- map_data("world")
base_map <- left_join(base_map, map_data, by = "region")

## now taking rid of the nas so only have country with data
basemap1 <- base_map %>% filter(!is.na(base_map$gender_equality_index_18))
## ok this worked but have too many lat and long measures for each country need to somehow get one for each

## going to see if I can summarize to just get mean score
basemap2 <- basemap1 %>% 
  group_by(region) %>% 
  summarize(hdi_rank, gender_equality_index_18, long, lat, rank_18, 
            maternal_mortality_ratio_15, adolescent_birth_rate_15_20, seats_in_parliment_18,
            secondary_education_m_10_18,
            secondary_education_f_10_18,
            labour_force_participation_f_18,
            labour_force_participation_m_18)
## ok this just rebuilt the same thing, need to some how just get one measure of lat and long for each country to set with data point



## trying to create map with leaflet
leaflet(options = leafletOptions(attributionControl = FALSE)) %>% 
  addProviderTiles(providers$OpenStreetMap) %>% 
  addScaleBar(position = "bottomleft") 




```



### useful old code
```{r}
## attempt at interactive map using ggplot
map1 <- ggplot(basemap1, aes(x = long, y = lat, group = group)) +
  geom_polygon(aes(fill = gender_equality_index_18), color = "black")

map2 <- map1 + 
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "none")
map2
```


